<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>sp</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>^\s*\}</string>
	<key>name</key>
	<string>Spanakopita</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#escaped-char</string>
		</dict>
		<dict>
			<key>contentName</key>
			<string>markup.underline.spanakopita</string>
			<key>match</key>
			<string>___.*$</string>
			<key>name</key>
			<string>meta.title.spanakopita</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>{</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.spanakopita</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>markup.raw.spanakopita</string>
			<key>end</key>
			<string>}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.spanakopita</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.code.spanakopita</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$base</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\[ *\[</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.spanakopita</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\] *\]</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.spanakopita</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.link.all.spanakopita</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>@</string>
					<key>contentName</key>
					<string>markup.underline.link.url.spanakopita</string>
					<key>end</key>
					<string>(?=\])</string>
					<key>name</key>
					<string>meta.link.url.spanakpoita</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escaped-char</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>$base</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.spanakopita</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>markup.underline.link.img.spanakopita</string>
			<key>end</key>
			<string>\]</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.spanakopita</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.img.spanakopita</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#escaped-char</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>__</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.spanakopita</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>markup.underline.spanakopita</string>
			<key>end</key>
			<string>__</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.spanakopita</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.underline.spanakopita</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$base</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\*\*</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.spanakopita</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>markup.bold.spanakopita</string>
			<key>end</key>
			<string>\*\*</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.spanakopita</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.bold.spanakopita</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$base</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>//</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.spanakopita</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>markup.italic.spanakopita</string>
			<key>end</key>
			<string>//</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.spanakopita</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.italic.spanakopita</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$base</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>escaped-char</key>
		<dict>
			<key>match</key>
			<string>\\.</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.spanakopita</string>
	<key>uuid</key>
	<string>853B9777-F557-4BBC-A476-DEDD6D2AE2B7</string>
</dict>
</plist>
